name: Run Gradle on push tag
on:
  push:
    tags:
      - '*'
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        name: gradle build
        with:
          arguments: build
      - uses: eskatos/gradle-command-action@v1
        name: gradle jib
        with:
          arguments: jib --image=docker.pkg.github.com/apstndb/zetasql-sandbox/zetasql-sandbox:${{ steps.get_version.outputs.VERSION }} -Djib.console=plain -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ github.token }}
